theme: jekyll-theme-slate
title: Heimdallr
description: Multi-Terrain Patrol, Security, and Surveillance Robot
show_downloads: false
google_analytics: UA-176925840-1
url: https://heimdallr-robot.github.io

collections:
  members:
    output: true
  documents:
    output: true

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
      portrait: "/assets/images/Portrait_Placeholder.png"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "documents"
    values:
      layout: "document"
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-postfiles
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links


